version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Expendi
    ports:
      - "3306:3306"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Path to the directory containing your backend Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Expendi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
   build:
    context: ./frontend
    dockerfile: Dockerfile
   ports:
      - "3000:80"
   depends_on:
      - backend
   environment:
      - REACT_APP_BACKEND_URL=http://backend:8080/


