version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Specify the path to your backend Dockerfile
    ports:
      - "9090:8080"  # Map container port 8080 to host port 8080
    depends_on:
      - database  # Ensure that the database service is running before starting the backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Specify the path to your frontend Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set the MySQL root password
      MYSQL_DATABASE: Expendi  # Create a database named 'Expendi'
    ports:
      - "3308:3306"
