version: '3.8'
services:
  db:
    image: ${containerRegistryURL}/devops/${imageName}/${dockerComposeDir}/${database}:${version}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    ports:
      - "3307:3306"

  backend:
    image: ${containerRegistryURL}/devops/${imageName}/${dockerComposeDir}/${backend}:${version}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Expendi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "8080:8080"
     

  frontend:
    image: ${containerRegistryURL}/devops/${imageName}/${dockerComposeDir}/${frontend}:${version}
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "3000:3000"

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
      name: db_data
