
name: Budget Application CI/CD with Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Building backend using Maven
      run: mvn clean install
      working-directory: backend

    - name: Running backend test using Maven
      run: mvn test
      working-directory: backend

